#!/usr/bin/env python3
"""Null-model honesty: selection-matched tests, pseudo de-duplication, palette substrings.

Recomputes the AUDIT_REVIEW matched p-range from the archived battery CSVs
and reports the 426-distinct-of-500 pseudoreplication (N1).

Does not re-run decoders.
"""
from __future__ import annotations

import csv
import glob
import os
import collections
from math import comb

HERE = os.path.dirname(os.path.abspath(__file__))

SEEDS = [1729, 9001, 271828, 42, 55555]


def fisher_greater(a, b, c, d):
    """One-sided Fisher exact, alternative=greater, table [[a,b],[c,d]].

    a = real passes, b = real fails, c = pseudo passes, d = pseudo fails.
    """
    n = a + b + c + d
    k = a + c
    # P(X >= a | hypergeometric)
    p = 0.0
    lo = max(0, k - (c + d))
    hi = min(k, a + b)
    for x in range(a, hi + 1):
        p += comb(a + b, x) * comb(c + d, k - x) / comb(n, k)
    return p


def load_battery(pattern):
    """Return list of (seed, id, type, string, confidence, root, lang, gloss)."""
    out = []
    for seed in SEEDS:
        keyp = os.path.join(HERE, f"blind_test_key_s{seed}.csv")
        resp = os.path.join(HERE, pattern.format(seed=seed))
        key = {}
        with open(keyp, encoding="utf-8") as f:
            for r in csv.DictReader(f):
                key[r["id"]] = r
        with open(resp, encoding="utf-8") as f:
            for r in csv.DictReader(f):
                k = key[r["id"]]
                out.append({
                    "seed": seed,
                    "id": r["id"],
                    "type": k["type"],
                    "string": k["string"],
                    "confidence": (r.get("confidence") or "").strip().lower(),
                    "root": r.get("root") or "",
                    "lang": r.get("lang") or "",
                    "gloss": r.get("gloss") or "",
                    "found": (r.get("found(Y/N)") or r.get("found") or "").strip().upper(),
                })
    return out


def main():
    A = load_battery("blind_test_results_s{seed}.csv")
    C = load_battery("blind_test_results_tight_s{seed}.csv")
    D = load_battery("blind_test_results_tight_online_s{seed}.csv")

    def arm(rows, typ):
        xs = [r for r in rows if r["type"] == typ]
        c = sum(1 for r in xs if r["confidence"] == "c")
        return c, len(xs)

    lines = []
    def emit(s=""):
        lines.append(s)
        print(s)

    emit("# Null-model honesty output")
    emit("")
    emit("Generated by `python3 null_honesty.py`. Recomputes AUDIT_REVIEW O1 / N1 from archived CSVs.")
    emit("")

    # Pooled A-D rates (legacy any-C)
    emit("## Legacy pooled any-C rates (reproduce published FPR/TPR)")
    emit("")
    emit("| Battery | Pseudo C | Real C | FPR | TPR |")
    emit("|---|---|---|---:|---:|")
    for name, rows in (("A loose offline", A), ("C strict offline", C), ("D strict online", D)):
        pc, pn = arm(rows, "pseudo")
        rc, rn = arm(rows, "real")
        emit(f"| {name} | {pc}/{pn} | {rc}/{rn} | {pc/pn:.3f} | {rc/rn:.3f} |")
    emit("")

    # Selection-matched: Battery A loose-C pseudo, then Battery D C on the same strings
    # Join by seed + string.
    def index(rows, typ):
        d = {}
        for r in rows:
            if r["type"] == typ:
                d[(r["seed"], r["string"])] = r
        return d

    A_p = index(A, "pseudo")
    D_p = index(D, "pseudo")
    A_r = index(A, "real")
    D_r = index(D, "real")
    C_p = index(C, "pseudo")
    C_r = index(C, "real")

    loose_pseudo = [k for k, r in A_p.items() if r["confidence"] == "c"]
    d_given_a = sum(1 for k in loose_pseudo if D_p[k]["confidence"] == "c")
    c_given_a = sum(1 for k in loose_pseudo if C_p[k]["confidence"] == "c")

    # Real arm: the 30 plants, trial-level (5 seeds x 30 = 150), but matched
    # comparison in the review uses 31 = the 30 plants? Wait.
    # AUDIT_REVIEW: "Matched within A to D, trial level: 19/31 vs 8/31"
    # 31 is the number of unique plant types that passed loose A? Or 31 trials?
    # Looking at the review: real 19/31 = 61.3%, same denominator as 8/31 pseudo.
    # So they took the 31 loose-committed PSEUDO items as the selection filter,
    # and for the REAL arm they used... 19/31?
    #
    # Re-read: "applying the same blind loose filter (Battery A) and the same
    # blind strict test (Battery D) to both arms"
    # Real: among the 30 plants, how many unique items were C in A and then C in D?
    # 30 plants, not 31.
    #
    # Trial level: 5 seeds * something.
    # 31 C in Battery A real pooled is 31/150 = 0.207, that's TPR not 19/31.
    #
    # 19/31: perhaps unique real tokens that were C in A (across seeds)?
    # 30 unique real plants. How many unique plants are C in A in at least one seed?
    #
    # Let's compute several reconstructions and report what actually rebuilds 19/31.

    emit("## Selection-matched comparisons (same filter on both arms)")
    emit("")
    emit(f"Battery A pseudo C (loose-committed noise): {len(loose_pseudo)} / 500")
    emit(f"Of those, Battery D C: {d_given_a}/{len(loose_pseudo)}")
    emit(f"Of those, Battery C C: {c_given_a}/{len(loose_pseudo)}")
    emit("")

    # Unique real plants
    plants = sorted({r["string"] for r in A if r["type"] == "real"})
    emit(f"Unique real plants: {len(plants)}")

    # Per-plant: C in A in >=1 seed, C in D in >=1 seed, C in D in all seeds, etc.
    def plant_c(idx, plant):
        hits = []
        for seed in SEEDS:
            r = idx.get((seed, plant))
            if r and r["confidence"] == "c":
                hits.append(seed)
        return hits

    a_c_plants = [p for p in plants if plant_c(A_r, p)]
    d_c_plants = [p for p in plants if plant_c(D_r, p)]
    both_ad = [p for p in plants if plant_c(A_r, p) and plant_c(D_r, p)]
    emit(f"Plants with at least one Battery A C: {len(a_c_plants)} / {len(plants)}")
    emit(f"Plants with at least one Battery D C: {len(d_c_plants)} / {len(plants)}")
    emit(f"Plants with A C and D C (item-level both filters): {len(both_ad)} / {len(a_c_plants) if a_c_plants else 0} among A-C plants")
    emit("")

    # Trial-level: among the 150 real trials, those that were C in A, how many C in D
    a_real_c_keys = [k for k, r in A_r.items() if r["confidence"] == "c"]
    d_among_a_real = sum(1 for k in a_real_c_keys if D_r[k]["confidence"] == "c")
    c_among_a_real = sum(1 for k in a_real_c_keys if C_r[k]["confidence"] == "c")
    emit(f"Trial-level: real A-C then D-C: {d_among_a_real}/{len(a_real_c_keys)}")
    emit(f"Trial-level: real A-C then C-C: {c_among_a_real}/{len(a_real_c_keys)}")
    emit("")

    # The review's 19/31: 31 A-C real trials? That's exactly len(a_real_c_keys) if it is 31.
    emit(f"Real A-C trial count (should be Battery A Real C = 31): {len(a_real_c_keys)}")
    emit("")

    # 19/31 vs 8/31
    real_n = len(a_real_c_keys)
    real_pass = d_among_a_real
    pseudo_n = len(loose_pseudo)
    pseudo_pass = d_given_a
    p_trial = fisher_greater(real_pass, real_n - real_pass, pseudo_pass, pseudo_n - pseudo_pass)
    emit(f"Matched A then D, trial level: real {real_pass}/{real_n} vs pseudo {pseudo_pass}/{pseudo_n}")
    emit(f"  Fisher one-sided p = {p_trial:.4g}")

    real_pass_c = c_among_a_real
    pseudo_pass_c = c_given_a
    p_trial_c = fisher_greater(real_pass_c, real_n - real_pass_c, pseudo_pass_c, pseudo_n - pseudo_pass_c)
    emit(f"Matched A then C offline, trial level: real {real_pass_c}/{real_n} vs pseudo {pseudo_pass_c}/{pseudo_n}")
    emit(f"  Fisher one-sided p = {p_trial_c:.4g}")
    emit("")

    # Item-level de-pseudoreplication: unique strings, not seed repeats.
    # Review: 6/9 vs 8/27, p=0.058
    # Unique pseudo strings that were A-C (any seed), then unique that were also D-C.
    # Unique real plants that were A-C, then also D-C.
    uniq_pseudo_ac = sorted({k[1] for k in loose_pseudo})
    uniq_pseudo_ac_dc = [s for s in uniq_pseudo_ac if any(D_p[(seed, s)]["confidence"] == "c" for seed in SEEDS if (seed, s) in D_p)]
    # A pseudo string appears in exactly one seed (generator per seed), so
    # joining by (seed,string) is the trial. Distinct strings across seeds: 426.
    # For item-level, collapse repeated strings that appear in multiple seeds.
    emit(f"Unique A-C pseudo strings: {len(uniq_pseudo_ac)}")
    emit(f"Unique A-C-and-D-C pseudo strings: {len(uniq_pseudo_ac_dc)}")
    emit(f"Unique A-C real plants: {len(a_c_plants)}")
    emit(f"Unique A-C-and-D-C real plants: {len(both_ad)}")
    p_item = fisher_greater(len(both_ad), len(a_c_plants) - len(both_ad),
                            len(uniq_pseudo_ac_dc), len(uniq_pseudo_ac) - len(uniq_pseudo_ac_dc))
    emit(f"Matched, de-pseudoreplicated to item level: real {len(both_ad)}/{len(a_c_plants)} vs pseudo {len(uniq_pseudo_ac_dc)}/{len(uniq_pseudo_ac)}")
    emit(f"  Fisher one-sided p = {p_item:.4g}")
    emit("")

    # CSV-verified unmatched pairing 21/61 vs 8/31
    p_old = fisher_greater(21, 40, 8, 23)
    p_pub = fisher_greater(23, 39, 8, 23)
    emit(f"Audit pairing (published 23/62 vs 8/31): p = {p_pub:.4g}")
    emit(f"Same pairing, CSV-verified 21/61 vs 8/31: p = {p_old:.4g}")
    emit("")
    emit("Honest headline (AUDIT_REVIEW O1): conditioning on selection collapses the")
    emit("claimed 2 x 10^-15 to a matched range. From this rebuild:")
    emit(f"  trial-level A then D  p = {p_trial:.4g}")
    emit(f"  trial-level A then C  p = {p_trial_c:.4g}")
    emit(f"  item-level            p = {p_item:.4g}")
    emit("Signal is marginal rather than overwhelming. Selection-conditioning is required.")
    emit("The old binomial against the unconditional 4.6% floor is withdrawn as a headline.")
    emit("")

    # Pseudo de-duplication
    emit("## Pseudo corpus pseudoreplication (N1)")
    emit("")
    all_pseudo = [r["string"] for r in A if r["type"] == "pseudo"]
    ctr = collections.Counter(all_pseudo)
    n_distinct = len(ctr)
    repeats = {s: n for s, n in ctr.items() if n > 1}
    emit(f"Pooled Battery A/C/D worksheets share the same 5 seeded pseudo lists.")
    emit(f"500 pseudo trials, **{n_distinct} distinct strings**. {len(repeats)} strings repeat across seeds.")
    top = sorted(repeats.items(), key=lambda x: -x[1])[:12]
    emit("Most repeated: " + ", ".join(f"{s} x{n}" for s, n in top))
    emit("")

    # Palette substrings
    palette = """
    Atziri Otsuks Tzokan'te u'te A'te Yatle ik'el Kuxkal tlayeb kutsen Ela ukto Maax ka ti
    a'tul cheyel mucane quxzeh Axba Kiibsa' ta' en Gyan'uks Donuks puxe daka jare fukuur soxsal
    puyao te'moxti nochbe inib buxa Eche lu Aiokmo akal anab ascensionada atla cha'tsoke chikula'
    ek elba Eztli Pilli Guatelitzi Ibil ich ikba'yucane ik'bala Ik'eche itsok itzil kifba kiimil
    kilya ko'janti kujkuali liimek Ma'oxe mujuk' naach nochira pochiti qexcan sakilja ta'nuk tala
    Teoyuxtlane til Tlaxye' Kextal uch' yuquia yutsal Xatlene Xibaqua Atzoatl Kuetzakala Quemalani
    Xolotl Tizoc Cotan Axilo Mektul Ahuatotli Xomatl tatlat xomaplat xictep cutlotl azcado huatat
    quiquate zahua moti taak'iin kahk tche ka'tse ipkaat koriek xecwa Napuatzi Doryani Zolin Zelina
    Kamasa Kopec Ketzuli Tetzlapokal Arakaali Kishara
    """.split()
    corpus_l = [w.lower() for w in palette]
    long = [w for w in corpus_l if len(w) >= 4]
    # substrings of committed tokens length >= 4 that appear as whole pseudo strings
    suspect = []
    spanishish = {"noche", "noch"}
    for s, n in ctr.items():
        sl = s.lower()
        why = []
        if sl in spanishish:
            why.append("ordinary Spanish word in a palette that includes Spanish loans")
        for rw in long:
            if sl != rw and sl in rw and len(sl) >= 4:
                why.append(f"substring of corpus token {rw}")
        if why:
            # was it C in any battery?
            ac = any(r["string"] == s and r["confidence"] == "c" for r in A + D)
            suspect.append((s, n, ac, "; ".join(why)))
    emit("Pseudo strings that are palette substrings or ordinary Spanish (N1):")
    emit("")
    emit("| string | seeds | any-C in A or D | why |")
    emit("|---|---:|---|---|")
    for s, n, ac, why in sorted(suspect, key=lambda x: -x[1]):
        emit(f"| {s} | {n} | {'yes' if ac else 'no'} | {why} |")
    emit("")
    emit("The generator claims to reject corpus words and long substrings; eztl (of Eztli)")
    emit("and noche show that guarantee is incomplete. Some noise-arm C labels are not noise.")
    emit("")
    emit("## De-duplicated null reporting")
    emit("")
    emit(f"Unconditional Battery D FPR on 500 trials: {arm(D,'pseudo')[0]}/500.")
    d_by_string = collections.defaultdict(list)
    for r in D:
        if r["type"] == "pseudo":
            d_by_string[r["string"]].append(r["confidence"] == "c")
    # Distinct-string FPR: a string is a hit if any of its seed copies was C,
    # or majority? Honest: unique strings, hit if the (usually single) trial was C.
    # For repeats, use the mean of copies then treat as one item: conservative
    # is "any C" (inflates FPR) vs "all C". Report unique-string rate as
    # fraction of distinct strings that were C in the seed they appear in.
    # Simpler: unique strings, C if ANY copy is C.
    uniq_c = sum(1 for s, hits in d_by_string.items() if any(hits))
    emit(f"Distinct-string Battery D FPR (any-copy C): {uniq_c}/{len(d_by_string)} = {uniq_c/len(d_by_string):.3f}")
    emit("Wilson / binomial intervals that treat n=500 as independent are too narrow.")
    emit("A full-pipeline simulation (commit then strict-gate on each unique pseudo) was not re-run;")
    emit("the matched A-then-D comparison above is the correction that the archived files support.")
    emit("")

    # Syntax Fisher at analyst level
    emit("## Syntax control, analyst-level Fisher (F8)")
    emit("")
    emit("Published: 12/12 vs 0/8 (3 analysts x 4 word-order rules vs 2 x 4), Fisher p ~ 7.9e-6.")
    emit("Experimental unit is analyst-by-corpus, not analyst-by-rule.")
    emit("Analyst-level table: 3/3 real analysts recovered order vs 0/2 scrambled.")
    p_syn = fisher_greater(3, 0, 0, 2)
    emit(f"Fisher one-sided 3/3 vs 0/2: p = {p_syn:.4g} (not significant).")
    emit("Analysts were given surface lines, English translations, and a token glossary")
    emit("(master §17.8). They were not blind to the project's readings.")
    emit("The design cannot support a significance claim. Reproducibility is qualitative.")
    emit("")

    path = os.path.join(HERE, "NULL_HONESTY_OUTPUT.md")
    with open(path, "w", encoding="utf-8") as f:
        f.write("\n".join(lines) + "\n")
    print(f"Wrote {path}")


if __name__ == "__main__":
    main()
