#!/usr/bin/env python3
"""Pool re-run Batteries A-D, write NULL_MODEL_RESULTS_RERUN.md.

Does not overwrite 2026-07 archives or NULL_HONESTY_OUTPUT.md.
"""
from __future__ import annotations

import argparse
import collections
import csv
import math
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, HERE)
from null_honesty import fisher_greater, SEEDS  # noqa: E402
from score import load_committed  # noqa: E402
from match_committed import fold, judge_decode  # noqa: E402

BAT = {
    "A": "blind_test_results_rerun_s{seed}.csv",
    "B": "blind_test_results_rerun_online_s{seed}.csv",
    "C": "blind_test_results_rerun_tight_s{seed}.csv",
    "D": "blind_test_results_rerun_tight_online_s{seed}.csv",
}


def wilson(k, n, z=1.96):
    if n <= 0:
        return 0.0, 0.0, 0.0
    p = k / n
    den = 1 + z * z / n
    centre = (p + z * z / (2 * n)) / den
    marg = z * math.sqrt((p * (1 - p) + z * z / (4 * n)) / n) / den
    return p, max(0.0, centre - marg), min(1.0, centre + marg)


def load_battery(pattern, key_pat="blind_test_key_rerun_s{seed}.csv"):
    out = []
    for seed in SEEDS:
        keyp = os.path.join(HERE, key_pat.format(seed=seed))
        resp = os.path.join(HERE, pattern.format(seed=seed))
        key = {}
        with open(keyp, encoding="utf-8") as f:
            for r in csv.DictReader(f):
                key[r["id"]] = r
        with open(resp, encoding="utf-8") as f:
            for r in csv.DictReader(f):
                k = key[r["id"]]
                out.append({
                    "seed": seed,
                    "id": r["id"],
                    "type": k["type"],
                    "string": k["string"],
                    "confidence": (r.get("confidence") or "").strip().lower(),
                    "root": r.get("root") or "",
                    "lang": r.get("lang") or "",
                    "gloss": r.get("gloss") or "",
                    "found": (r.get("found(Y/N)") or r.get("found") or "").strip().upper(),
                    "residue": r.get("residue") or "",
                    "notes": r.get("notes") or "",
                    "row": r,
                })
    return out


def recovery_of(row, committed):
    if row["type"] == "pseudo":
        return "n/a"
    rec = committed.get(fold(row["string"]))
    if rec is None:
        return "unscorable"
    return judge_decode(rec, row["row"])["recovery"]


def arm(rows, typ, conf="c"):
    xs = [r for r in rows if r["type"] == typ]
    c = sum(1 for r in xs if r["confidence"] == conf)
    return c, len(xs)


def pct(k, n):
    p, lo, hi = wilson(k, n)
    return f"{k}/{n} = {p:.3f} [{lo:.3f}, {hi:.3f}]"


def main(argv=None):
    p = argparse.ArgumentParser()
    p.add_argument("--committed", default=os.path.join(HERE, "committed_readings.csv"))
    args = p.parse_args(argv)
    committed = load_committed(args.committed) if os.path.isfile(args.committed) else {}

    data = {name: load_battery(pat) for name, pat in BAT.items()}
    for name, rows in data.items():
        for r in rows:
            r["recovery"] = recovery_of(r, committed)

    lines = []
    def emit(s=""):
        lines.append(s)

    emit("# Null-model results (re-run epoch)")
    emit("")
    emit("Generated by `python3 rerun_score_pool.py`. Decoder: form-first lookup over attached")
    emit("text dictionaries (`dict_lookup.py`, `decode_blind.py`). Worksheets from")
    emit("`generate_pseudo_vaal.py --rerun` (500 distinct pseudo strings, 30 plants x 5 seeds).")
    emit("This file does not replace the 2026-07 `NULL_MODEL_RESULTS.md`.")
    emit("")
    emit("Blinding: the decoder read only worksheets. It did not open keys, committed_readings,")
    emit("or master section 9/17 while filling sheets. Scoring below joins keys after the fact.")
    emit("")

    emit("## Pooled any-C rates (legacy diagnostic)")
    emit("")
    emit("| Battery | Pseudo C | Real C | FPR(C) | TPR(C) any-root | FPR(C+soft) | TPR(found) | Disc(C) |")
    emit("|---|---|---|---:|---:|---:|---:|---:|")
    pooled = {}
    for name in "A", "B", "C", "D":
        rows = data[name]
        pc, pn = arm(rows, "pseudo")
        rc, rn = arm(rows, "real")
        ps = sum(1 for r in rows if r["type"] == "pseudo" and r["confidence"] in ("c", "soft"))
        rf = sum(1 for r in rows if r["type"] == "real" and r["found"] == "Y")
        fpr, tpr = pc / pn, rc / rn
        fprs, tprf = ps / pn, rf / rn
        pooled[name] = dict(pc=pc, pn=pn, rc=rc, rn=rn, ps=ps, rf=rf, fpr=fpr, tpr=tpr)
        emit(f"| {name} | {pc}/{pn} | {rc}/{rn} | {fpr:.3f} | {tpr:.3f} | {fprs:.3f} | {tprf:.3f} | {tpr-fpr:+.3f} |")
    emit("")
    emit("Wilson 95% CI:")
    emit("")
    emit("| Battery | FPR(C) | TPR(C) any-root |")
    emit("|---|---|---|")
    for name in "A", "B", "C", "D":
        d = pooled[name]
        _, flo, fhi = wilson(d["pc"], d["pn"])
        _, tlo, thi = wilson(d["rc"], d["rn"])
        emit(f"| {name} | {d['fpr']:.3f} [{flo:.3f}, {fhi:.3f}] | {d['tpr']:.3f} [{tlo:.3f}, {thi:.3f}] |")
    emit("")

    emit("## Distinct-string FPR (primary noise floor)")
    emit("")
    for name in "A", "C", "D":
        rows = [r for r in data[name] if r["type"] == "pseudo"]
        by = collections.defaultdict(list)
        for r in rows:
            by[r["string"].lower()].append(r["confidence"] == "c")
        uniq_c = sum(1 for hits in by.values() if any(hits))
        emit(f"- Battery {name}: {uniq_c}/{len(by)} = {uniq_c/len(by):.3f} (any-copy C on distinct strings). Trials {len(rows)}, distinct {len(by)}.")
    emit("")
    emit("Cross-seed nonce repeats: none (distinct == trials by construction).")
    emit("")

    emit("## Recovery TPR (real arm, committed root/lang/sense)")
    emit("")
    emit("A real plant is a recovery TP only if confidence is C and the decode matches")
    emit("`committed_readings.csv` on root, language class, and sense. Pseudo C remains a")
    emit("false positive (no committed reading). Empty C never occurs in this epoch.")
    emit("")
    emit("| Battery | Recovery yes | mismatch | unscorable | n real | TPR(recovery) |")
    emit("|---|---:|---:|---:|---:|---:|")
    recov = {}
    for name in "A", "B", "C", "D":
        real = [r for r in data[name] if r["type"] == "real"]
        yes = sum(1 for r in real if r["recovery"] == "yes")
        no = sum(1 for r in real if r["recovery"] == "no")
        un = sum(1 for r in real if r["recovery"] == "unscorable")
        recov[name] = dict(yes=yes, no=no, un=un, n=len(real))
        emit(f"| {name} | {yes} | {no} | {un} | {len(real)} | {yes/len(real):.3f} |")
    emit("")
    emit("Unscorable plant: *Otsuks* is in the 30-plant list but has no row in")
    emit("`committed_readings.csv` (no predeclared root/lang/sense). Five trials (one per seed).")
    emit("")

    # Selection-matched any-C
    A, D, C = data["A"], data["D"], data["C"]
    def index(rows, typ):
        return {(r["seed"], r["string"]): r for r in rows if r["type"] == typ}

    A_p, D_p, C_p = index(A, "pseudo"), index(D, "pseudo"), index(C, "pseudo")
    A_r, D_r, C_r = index(A, "real"), index(D, "real"), index(C, "real")

    loose_pseudo = [k for k, r in A_p.items() if r["confidence"] == "c"]
    d_given_a = sum(1 for k in loose_pseudo if D_p[k]["confidence"] == "c")
    c_given_a = sum(1 for k in loose_pseudo if C_p[k]["confidence"] == "c")
    a_real_c_keys = [k for k, r in A_r.items() if r["confidence"] == "c"]
    d_among_a_real = sum(1 for k in a_real_c_keys if D_r[k]["confidence"] == "c")
    c_among_a_real = sum(1 for k in a_real_c_keys if C_r[k]["confidence"] == "c")

    p_trial = fisher_greater(d_among_a_real, len(a_real_c_keys) - d_among_a_real,
                             d_given_a, len(loose_pseudo) - d_given_a)

    plants = sorted({r["string"] for r in A if r["type"] == "real"})
    def plant_c(idx, plant):
        return [seed for seed in SEEDS if idx.get((seed, plant)) and idx[(seed, plant)]["confidence"] == "c"]
    a_c_plants = [p for p in plants if plant_c(A_r, p)]
    both_ad = [p for p in plants if plant_c(A_r, p) and plant_c(D_r, p)]
    uniq_pseudo_ac = sorted({k[1] for k in loose_pseudo})
    uniq_pseudo_ac_dc = [s for s in uniq_pseudo_ac if any(
        D_p.get((seed, s)) and D_p[(seed, s)]["confidence"] == "c" for seed in SEEDS)]
    p_item = fisher_greater(len(both_ad), len(a_c_plants) - len(both_ad),
                            len(uniq_pseudo_ac_dc), len(uniq_pseudo_ac) - len(uniq_pseudo_ac_dc))

    emit("## Selection-matched Fisher (any-C, A then D)")
    emit("")
    emit(f"Battery A pseudo C: {len(loose_pseudo)} / 500. Of those, Battery D C: {d_given_a}/{len(loose_pseudo)}.")
    emit(f"Trial-level real A-C then D-C: {d_among_a_real}/{len(a_real_c_keys)}.")
    emit(f"Matched A then D, trial level: real {d_among_a_real}/{len(a_real_c_keys)} vs pseudo {d_given_a}/{len(loose_pseudo)}")
    emit(f"  Fisher one-sided p = {p_trial:.4g}")
    emit(f"Unique A-C plants: {len(a_c_plants)} / {len(plants)}; A-C and D-C: {len(both_ad)}.")
    emit(f"Unique A-C pseudo strings: {len(uniq_pseudo_ac)}; also D-C: {len(uniq_pseudo_ac_dc)}.")
    emit(f"Matched, item level: real {len(both_ad)}/{len(a_c_plants) if a_c_plants else 0} vs pseudo {len(uniq_pseudo_ac_dc)}/{len(uniq_pseudo_ac)}")
    emit(f"  Fisher one-sided p = {p_item:.4g}")
    emit("")
    p_trial_c = fisher_greater(c_among_a_real, len(a_real_c_keys) - c_among_a_real,
                               c_given_a, len(loose_pseudo) - c_given_a)
    emit(f"Matched A then C offline, trial level: real {c_among_a_real}/{len(a_real_c_keys)} vs pseudo {c_given_a}/{len(loose_pseudo)}")
    emit(f"  Fisher one-sided p = {p_trial_c:.4g}")
    emit("")

    # Recovery-scored matched: A C (any, the loose-commitment filter) then D recovery-yes
    d_rec_given_a = sum(1 for k in loose_pseudo if D_p[k]["recovery"] == "yes")  # always n/a for pseudo
    # Pseudo recovery is n/a; a pseudo C that stays C on D is still a FP.
    d_c_given_a_pseudo = d_given_a  # pseudo has no recovery yes
    d_rec_among_a_real = sum(1 for k in a_real_c_keys if D_r[k]["recovery"] == "yes")
    p_rec_trial = fisher_greater(d_rec_among_a_real, len(a_real_c_keys) - d_rec_among_a_real,
                                 d_c_given_a_pseudo, len(loose_pseudo) - d_c_given_a_pseudo)

    both_ad_rec = [p for p in plants if plant_c(A_r, p) and any(
        D_r.get((seed, p)) and D_r[(seed, p)]["recovery"] == "yes" for seed in SEEDS)]
    # item-level pseudo: unique A-C strings that are D C (still FP)
    p_rec_item = fisher_greater(len(both_ad_rec), len(a_c_plants) - len(both_ad_rec),
                                len(uniq_pseudo_ac_dc), len(uniq_pseudo_ac) - len(uniq_pseudo_ac_dc))

    emit("## Selection-matched Fisher (recovery-scored where possible)")
    emit("")
    emit("Loose filter is still Battery A any-C (commitment to some attested root).")
    emit("Strict arm for the real plants is Battery D **recovery-yes**. Strict arm for")
    emit("pseudo remains Battery D any-C (pseudos have no committed reading, so a C is a FP).")
    emit("")
    emit(f"Trial-level: real A-C then D-recovery: {d_rec_among_a_real}/{len(a_real_c_keys)} vs pseudo A-C then D-C: {d_c_given_a_pseudo}/{len(loose_pseudo)}")
    emit(f"  Fisher one-sided p = {p_rec_trial:.4g}")
    emit(f"Item-level: real A-C plants with a D-recovery in any seed: {len(both_ad_rec)}/{len(a_c_plants) if a_c_plants else 0} vs pseudo {len(uniq_pseudo_ac_dc)}/{len(uniq_pseudo_ac)}")
    emit(f"  Fisher one-sided p = {p_rec_item:.4g}")
    emit("")
    emit("No unconditional binomial against a 4.6% floor is reported. No sigma label.")
    emit("")

    emit("## Notes")
    emit("")
    emit("- Online Nahuatl (Battery B/D extra lexicon: Nahuatl 1100 wordlist plus Campbell CN")
    emit("  citations) moves a few C labels relative to offline. Discrimination does not widen.")
    emit("- Recovery TPR is far below any-C TPR: exact dictionary hits often attach a")
    emit("  different sense or language than `committed_readings.csv` (the F1 hole, re-measured).")
    emit("- *naach* recovers (lejos / distant). *ek* is C as wasp, not star/dark.")
    emit("- Ordinary Spanish exact hits are labelled Spanish C, not 'pure noise'. The generator")
    emit("  also excluded those strings from the pseudo arm.")
    emit("")

    path = os.path.join(HERE, "NULL_MODEL_RESULTS_RERUN.md")
    with open(path, "w", encoding="utf-8") as f:
        f.write("\n".join(lines) + "\n")
    print(f"Wrote {path}")
    print(f"A FPR {pooled['A']['fpr']:.3f} TPR {pooled['A']['tpr']:.3f}")
    print(f"D FPR {pooled['D']['fpr']:.3f} TPR {pooled['D']['tpr']:.3f}")
    print(f"matched A-then-D trial p={p_trial:.4g} item p={p_item:.4g}")
    print(f"recovery-matched trial p={p_rec_trial:.4g} item p={p_rec_item:.4g}")


if __name__ == "__main__":
    main()
